#!/usr/bin/env ruby

require 'nokogiri'
require 'net/http'

require_relative 'jobs'

SOURCE = 'http://inkdroid.org/vine/'

loop do
  page = `curl -s #{SOURCE}`
  doc = Nokogiri.HTML(page)
  ing = Inkdroid::Ingester.new

  (doc/'td a').select { |a| a['href'] =~ /[0-9]+\.txt/ }.each do |a|
    url = URI.join(SOURCE, a['href']).to_s
    ing.perform(url)
  end

  sleep 600
end
