#!/usr/bin/env ruby

require 'nokogiri'
require 'net/http'

require_relative 'http_ingester'

SOURCE = 'http://vine.inkdroid.org/'

loop do
  page = `curl -s #{SOURCE}`
  doc = Nokogiri.HTML(page)
  ing = Inkdroid::HttpIngester.new

  (doc/'td a').select { |a| a['href'] =~ /[0-9]+\.txt$/ }.each do |a|
    url = URI.join(SOURCE, a['href']).to_s
    ing.perform(url)
  end

  sleep 600
end
